WEIGHT_MAX: int

class PyEdge:
    def from_node(self) -> int: ...
    def to_node(self) -> int: ...
    def weight(self) -> int: ...

class PyInputGraph:
    def __init__(cls) -> PyInputGraph: ...
    def add_edge(self, from_: int, to: int, weight: int) -> int: ...
    def add_edge_bidir(self, from_: int, to: int, weight: int) -> int: ...
    def freeze(self) -> None: ...
    def thaw(self) -> None: ...
    def get_num_nodes(self) -> int: ...
    def get_num_edges(self) -> int: ...
    def get_edges(self) -> list[PyEdge]: ...
    def to_file(self, filename: str) -> None: ...
    @staticmethod
    def from_file(filename: str) -> PyInputGraph: ...
    def to_dimacs_file(self, filename: str) -> None: ...
    @staticmethod
    def from_dimacs_file(filename: str) -> PyInputGraph: ...
    def unit_test_output_string(self) -> str: ...

class PyFastGraph:
    def calc_path(self, source: int, target: int) -> PyShortestPath | None: ...
    def get_node_ordering(self) -> list[int]: ...
    def get_num_nodes(self) -> int: ...
    def get_num_out_edges(self) -> int: ...
    def get_num_in_edges(self) -> int: ...
    def begin_in_edges(self, node: int) -> int: ...
    def end_in_edges(self, node: int) -> int: ...
    def begin_out_edges(self, node: int) -> int: ...
    def end_out_edges(self, node: int) -> int: ...

class PyFastGraph32: ...

class PyShortestPath:
    def get_weight(self) -> int: ...
    def get_nodes(self) -> list[int]: ...
    def get_source(self) -> int: ...
    def get_target(self) -> int: ...
    def is_found(self) -> bool: ...

class PyPathCalculator:
    def __init__(cls, num_nodes: int) -> PyPathCalculator: ...
    def calc_path(self, py_graph: PyFastGraph, source: int, target: int) -> PyShortestPath | None: ...
    def calc_path_multiple_sources_and_targets(
        self,
        py_graph: PyFastGraph,
        sources: list[tuple[int, int]],
        targets: list[tuple[int, int]],
    ) -> PyShortestPath | None: ...

class PyParams:
    def __init__(
        cls,
        hierarchy_depth_factor: float = 0.5,
        edge_quotient_factor: float = 1.0,
        max_initial: int = 100,
        max_neighbor: int = 200,
        max_contraction: int = 300,
    ) -> PyParams: ...
    @staticmethod
    def default() -> PyParams: ...
    def get_hierarchy_depth_factor(self) -> float: ...
    def set_hierarchy_depth_factor(self, v: float) -> None: ...
    def get_edge_quotient_factor(self) -> float: ...
    def set_edge_quotient_factor(self, v: float) -> None: ...
    def get_max_settled_nodes_initial_relevance(self) -> int: ...
    def set_max_settled_nodes_initial_relevance(self, v: int) -> None: ...
    def get_max_settled_nodes_neighbor_relevance(self) -> int: ...
    def set_max_settled_nodes_neighbor_relevance(self, v: int) -> None: ...
    def get_max_settled_nodes_contraction(self) -> int: ...
    def set_max_settled_nodes_contraction(self, v: int) -> None: ...

class PyParamsWithOrder:
    def __init__(cls, max_settled_nodes_contraction_with_order: int) -> PyParamsWithOrder: ...
    def get_max_settled_nodes_contraction_with_order(self) -> int: ...
    def set_max_settled_nodes_contraction_with_order(self, v: int) -> None: ...

class PyFastGraphBuilder: ...

# Top-level functions
def prepare(input_graph: PyInputGraph) -> PyFastGraph: ...
def prepare_with_params(input_graph: PyInputGraph, params: PyParams) -> PyFastGraph: ...
def prepare_with_order(input_graph: PyInputGraph, order: list[int]) -> PyFastGraph: ...
def prepare_with_order_with_params(
    input_graph: PyInputGraph, order: list[int], params: PyParamsWithOrder
) -> PyFastGraph: ...
def create_calculator(py_graph: PyFastGraph) -> PyPathCalculator: ...
def calc_path(py_graph: PyFastGraph, source: int, target: int) -> PyShortestPath | None: ...
def calc_path_multiple_sources_and_targets(
    py_graph: PyFastGraph,
    sources: list[tuple[int, int]],
    targets: list[tuple[int, int]],
) -> PyShortestPath | None: ...
